### PR TITLE
Change CI systems

### PR DESCRIPTION
**Pull request by zaro0508**
Move to use github action CI instead of travis ci. This CI setup is based on packer-ami-template[1]

[1] https://github.com/Sage-Bionetworks-IT/packer-ami-template

### CODE REVIEW

**Review by xschildw — APPROVED** [review]
So no need for anything about the srcImage anymore?

**Comment by zaro0508** [comment]
> So no need for anything about the srcImage anymore?

i don't understand your question @xschildw .  could you please clarify?

**Comment by xschildw** [comment]
I noticed that the packer commands used to have a parameter '-var SourceImage' that is not used anymore in the new version. Just curious...

**Comment by zaro0508** [comment]
Nice catch @xschildw, i forgot to update the template.json to match the new github build file.  The `source_ami_filter` gets the latest image which replaces specifying a specific image ID with `SourceImage`

**Review by xschildw — APPROVED** [review]

**Pull request merged**
